site_name: MCP Audio Server
site_description: Model Context Protocol server for audio processing and musical analysis
site_author: MCP Audio Server Team
repo_url: https://github.com/yourusername/mcp-audio-server
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference:
    - Overview: api/overview.md
    - OpenAPI Spec: api/openapi.md
    - Error Codes: api/errors.md
  - Developer Guide:
    - Getting Started: dev/getting-started.md
    - Environment Setup: dev/environment.md
    - Testing: dev/testing.md
    - Contributing: dev/contributing.md
  - Release Notes: changelog.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
  - autorefs
  - swagger-ui-tag:
      background: white
      docs_dir: docs/api

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/mcp-audio-server
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css
