global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mcp-audio-server'
    static_configs:
      - targets: ['mcp-audio-server:8001']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
