---
openapi: 3.0.3
info:
  title: MCP Audio Server
  description: |
    Model Context Protocol server for audio processing and musical analysis.
    This API provides endpoints for analyzing audio files to extract musical 
    features like chords, key, and tempo.
  version: 1.0.0
  contact:
    name: MCP Audio Server Team
    url: https://github.com/yourusername/mcp-audio-server
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000
    description: Local development server

tags:
  - name: analysis
    description: Audio analysis endpoints
  - name: monitoring
    description: Health and monitoring endpoints

paths:
  /analyze_chords:
    post:
      summary: Analyze chords in audio
      description: |
        Analyzes the submitted audio data and extracts musical features including
        chords, key, and tempo.
        
        The audio data must be base64-encoded and in a supported format (WAV,
        MP3, OGG, FLAC, M4A).
      operationId: analyzeChords
      tags:
        - analysis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChordAnalysisRequest'
            examples:
              wav_example:
                summary: WAV file example
                value:
                  audio_data: "UklGRiQEAABXQVZFZm10IBAAAAABAAIARKwAABCxAgAEACAAAABkYXRhAuLi4uLi4uLi"
                  format: "wav"
                  options:
                    model: "basic"
      responses:
        '200':
          description: Successful analysis
          headers:
            X-Correlation-ID:
              schema:
                type: string
              description: Correlation ID for request tracking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChordAnalysisResponse'
              examples:
                chord_analysis:
                  summary: Analysis result example
                  value:
                    schema_version: "1.0.0"
                    key: "C"
                    tempo: 120.0
                    chords:
                      - time: 0.0
                        label: "C"
                        confidence: 0.9
                      - time: 1.0
                        label: "G"
                        confidence: 0.85
                    duration: 4.0
                    processing_info:
                      sample_rate: 44100
                      channels: 1
                      processing_time: 0.245
                      model_used: "basic"
                    correlation_id: "550e8400-e29b-41d4-a716-446655440000"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                decoding_error:
                  summary: Audio decoding error
                  value:
                    error_code: "DECODING_ERROR"
                    message: "Failed to decode audio file: Invalid file format"
                    details:
                      format: "wav"
                      error: "Invalid WAV header"
                    correlation_id: "550e8400-e29b-41d4-a716-446655440000"
        '413':
          description: Audio file too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Server busy
          headers:
            Retry-After:
              schema:
                type: integer
              description: Number of seconds to wait before retrying
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server_busy:
                  summary: Server busy error
                  value:
                    error_code: "SERVER_BUSY"
                    message: "Server is currently busy. Please retry after 5 seconds."
                    details:
                      retry_after: 5
                    correlation_id: "550e8400-e29b-41d4-a716-446655440000"

  /health:
    get:
      summary: Basic health check
      description: Returns the server's health status
      operationId: healthCheck
      tags:
        - monitoring
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  uptime:
                    type: number
                    description: Server uptime in seconds
                    example: 3600
                  timestamp:
                    type: string
                    format: date-time
                    example: "2023-04-18T12:00:00Z"
                  version:
                    type: string
                    example: "1.0.0"

  /ready:
    get:
      summary: Readiness check
      description: |
        Returns the server's readiness status, including the status of external
        dependencies.
        
        This endpoint is intended for load balancers and orchestration systems.
      operationId: readinessCheck
      tags:
        - monitoring
      responses:
        '200':
          description: Server is ready to accept requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  checks:
                    type: object
                    properties:
                      ffmpeg:
                        type: boolean
                        example: true
                      models:
                        type: boolean
                        example: true
                  timestamp:
                    type: string
                    format: date-time
                    example: "2023-04-18T12:00:00Z"
        '503':
          description: Server is not ready
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "degraded"
                  checks:
                    type: object
                    properties:
                      ffmpeg:
                        type: boolean
                        example: false
                      models:
                        type: boolean
                        example: true
                  timestamp:
                    type: string
                    format: date-time
                    example: "2023-04-18T12:00:00Z"

components:
  schemas:
    ChordAnalysisRequest:
      type: object
      required:
        - audio_data
        - format
      properties:
        audio_data:
          type: string
          description: Base64-encoded audio data
        format:
          type: string
          description: Format of the audio data
          enum:
            - wav
            - mp3
            - ogg
            - flac
            - m4a
        options:
          type: object
          description: Analysis options
          properties:
            model:
              type: string
              description: Model to use for analysis
              enum:
                - basic
                - advanced
              default: basic

    ChordAnalysisResponse:
      type: object
      required:
        - schema_version
        - chords
        - duration
        - correlation_id
      properties:
        schema_version:
          type: string
          description: Version of the response schema
        key:
          type: string
          description: Musical key of the audio
          nullable: true
        tempo:
          type: number
          format: float
          description: Tempo in beats per minute
          nullable: true
        chords:
          type: array
          description: Detected chords with timestamps
          items:
            $ref: '#/components/schemas/ChordEntry'
        duration:
          type: number
          format: float
          description: Duration of the audio in seconds
        processing_info:
          $ref: '#/components/schemas/ProcessingInfo'
          nullable: true
        correlation_id:
          type: string
          description: Request correlation ID for tracking

    ChordEntry:
      type: object
      required:
        - time
        - label
      properties:
        time:
          type: number
          format: float
          description: Time position in seconds
        label:
          type: string
          description: Chord label (e.g., 'C', 'G7', 'Dm')
        confidence:
          type: number
          format: float
          description: Confidence score (0-1)
          nullable: true
          minimum: 0
          maximum: 1

    ProcessingInfo:
      type: object
      required:
        - sample_rate
        - processing_time
        - model_used
      properties:
        sample_rate:
          type: integer
          description: Sample rate used for analysis
        channels:
          type: integer
          description: Number of audio channels used
          default: 1
        processing_time:
          type: number
          format: float
          description: Time taken to analyze the audio in seconds
        model_used:
          type: string
          description: Chord detection model used for analysis

    ErrorResponse:
      type: object
      required:
        - error_code
        - message
        - correlation_id
      properties:
        error_code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        details:
          type: object
          description: Additional error details
          nullable: true
        correlation_id:
          type: string
          description: Request correlation ID for tracking
